name: protobuf-multipass
summary: Protocol Buffers compiler
description: >
  Protocol Buffers (a.k.a., protobuf) are Google's language-neutral,
  platform-neutral, extensible mechanism for serializing structured
  data. You can find protobuf's documentation at
  https://developers.google.com/protocol-buffers/
  This is intended for Multipass development.

type: app
adopt-info: protobuf
base: core18
confinement: strict
grade: stable

apps:
  protoc:
    command: bin/protoc
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$LD_LIBRARY_PATH

parts:
  protobuf:
    plugin: autotools
    source: https://github.com/protocolbuffers/protobuf.git
    source-type: git
    source-tag: v3.13.0
    override-build: |
      snapcraftctl build
      VERSION=$( git -C ${SNAPCRAFT_PART_SRC} describe --dirty --always --tags | sed -r 's/v(.*)/\1/g' )
      snapcraftctl set-version ${VERSION}
